### ISSUE TITLE
missing-http.jar is missing

### ISSUE THREAD

**Issue by rap9430** [psexton/missing-http#6]
the onLoad function looks for the file .../missing-http\java\dist\missing-http.jar
In my distribution there is no "dist" folder with this file.

**Comment by rap9430** [comment]
ok. I found it in the zip file.

**Comment by ivonascimento** [comment]
Hi,

I cannot find the "java\dist\missing-http.jar" in the latest version.
There is no dist folder as well.
Can anyone help me with that?

Thanks
